version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: marketapp
    ports:
      - "3306:3306"
    volumes:
      - ./data/marketapp.sql:/docker-entrypoint-initdb.d/marketapp.sql